version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    environment:
      - AWS_REGION=eu-central-1
      - COUNTER_TABLE_NAME=NumberAcidizer-local
      - AUDIT_TABLE_NAME=NumberAcidizer-local-audit
      - CONNECTIONS_TABLE_NAME=WebSocketConnections-local
      - ENVIRONMENT=local
      - PORT=3001
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - dynamodb-local
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_WS_URL=ws://localhost:3001
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
    networks:
      - app-network

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - '8000:8000'
    command: '-jar DynamoDBLocal.jar -inMemory -sharedDb'
    networks:
      - app-network

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - '8001:8001'
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dynamodb_data:
