name: Performance Tests

on:
  schedule:
    # Run at 2 AM UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

env:
  AWS_REGION: us-east-1
  NODE_VERSION: 18

jobs:
  performance-test:
    name: Performance Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install Dependencies
        run: |
          cd backend
          npm ci
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Get API Endpoint
        id: get-endpoint
        run: |
          if [ "${{ github.event.inputs.environment || 'staging' }}" = "production" ]; then
            echo "api_url=https://api.numberacidizer.com" >> $GITHUB_OUTPUT
          else
            echo "api_url=https://staging-api.numberacidizer.com" >> $GITHUB_OUTPUT
          fi
          
      - name: Run Performance Tests
        env:
          API_URL: ${{ steps.get-endpoint.outputs.api_url }}
        run: |
          cd backend
          npm run test:performance
          
      - name: Upload Performance Results
        uses: actions/upload-artifact@v3
        with:
          name: performance-results-${{ github.run_id }}
          path: backend/performance-results.json
          retention-days: 30
          
      - name: Check Performance Thresholds
        run: |
          cd backend
          node -e "
          const results = require('./performance-results.json');
          const failed = [];
          
          // Check thresholds
          if (results.lightLoad.averageResponseTime > 200) {
            failed.push('Light load avg response time > 200ms');
          }
          if (results.moderateLoad.successRate < 0.9) {
            failed.push('Moderate load success rate < 90%');
          }
          if (results.heavyLoad.percentiles.p95 > 2000) {
            failed.push('Heavy load p95 > 2000ms');
          }
          
          if (failed.length > 0) {
            console.error('Performance thresholds failed:');
            failed.forEach(f => console.error('  - ' + f));
            process.exit(1);
          }
          
          console.log('All performance thresholds passed!');
          "
          
      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Performance Test Failed',
              body: `Performance tests failed on ${new Date().toISOString()}\n\nEnvironment: ${{ github.event.inputs.environment || 'staging' }}\n\nCheck the workflow run for details: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              labels: ['performance', 'automated']
            })
